### ISSUE TITLE
not installed (windows 8)

### ISSUE THREAD

**Issue by Semigradsky** [SitePen/dts-generator#13]
```
> dts-generator@1.3.0-pre install E:\Dmitry\git\math\math-interval-parser\node_m
odules\dts-generator
> node -e "require('child_process').exec(require.resolve('typescript/bin/tsc') +
 ' -m commonjs -t es5 bin/dts-generator.ts index.ts', function(error, stdout, st
derr){stdout&&process.stdout.write(stdout);stderr&&process.stderr.write(stderr);
if(error)process.exit(1);})"


[eval]:1
"require('child_process').exec(require.resolve('typescript/bin/tsc')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:532:25)
    at startup (node.js:80:7)
    at node.js:902:3
```

**Comment by Semigradsky** [comment]
Maybe this commit can help: https://github.com/jzalucki/dts-generator/commit/c648134461ea1f430fd40a1a197a6606a80377c3

**Comment by csnover** [comment]
Since 1.3.0 when we can get a stable version of TypeScript with the necessary features, the code is generated prior to being uploaded to npm, so just `npm install dts-generator` and this should be resolved now!
