### ISSUE TITLE
Doesn't seem to work with ES6 import and d.ts files.

### ISSUE THREAD

**Issue by bab5139** [SitePen/dts-generator#42]
test.d.ts file:
```javascript
import 'angular';
export default class Test  {
    constructor();
    test(name: string): void;
}
```
Generator config:
```javascript
dtsGenerator.generate({
        name: 'Test',
        baseDir: 'wwwroot',
        files: [  'test.d.ts' ],
        externs:[ 'angular.d.ts' ],
        out: 'out.d.ts'
        //main: 'Planck'
    }
```
The angular.d.ts file was placed in the same directory as the test.d.ts file.  This fails for any external d.ts file I try to import, angular, rx, jquery.  

Exception Message:
```
Possibly unhandled TypeError: Cannot read property 'kind' of undefined
    at d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\dts-generator\index.js:163:33
    at visit (d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\dts-generator\index.js:54:27)
    at visitNode (d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\typescript\lib\typescript.js:7197:20)
    at Object.forEachChild (d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\typescript\lib\typescript.js:7468:21)
    at visit (d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\dts-generator\index.js:60:16)
    at visitEachNode (d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\typescript\lib\typescript.js:7209:30)
    at Object.forEachChild (d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\typescript\lib\typescript.js:7360:24)
    at visit (d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\dts-generator\index.js:60:16)
    at processTree (d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\dts-generator\index.js:63:5)
    at writeDeclaration (d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\dts-generator\index.js:152:27)
    at d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\dts-generator\index.js:124:17
    at Array.some (native)
    at d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\dts-generator\index.js:112:34
    at tryCatcher (d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\dts-generator\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._resolveFromResolver (d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\dts-generator\node_modules\bluebird\js\main\promise.js:448:31)
    at new Promise (d:\dev\proj\slb\planck\Client.Web\Client.Web.Framework\node_modules\dts-generator\node_modules\bluebird\js\main\promise.js:55:37)
[20:12:00] Finished 'bundle-dts' after 6.55 s
```

**Comment by stephenlautier** [comment]
This works for me, you need to specify the `tsd.d.ts` file within the files, also files need to be the `.ts` and not `d.ts` e.g.

```
files: ["./test.ts", `../tools/typings/tsd.d.ts`]
```
Externs simply adds references string within file, it should be like:
```
externs: ["../angularjs/angular.d.ts"]
```

Hope this helps

**Comment by bab5139** [comment]
That is what I needed!  I have no clue why I read that the d.ts files needed to be in the files array.  I even repeated that to myself last night looking at the code and pondering why the d.ts were being sent back to the compiler.  Thank you so much for the quick response.

**Comment by kitsonk** [comment]
Sounds like it is resolved.
