### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by dougludlow** [SitePen/dts-generator#58]
I'm attempting to generate a .d.ts for angular2, but I'm getting the following exception:

```
Unhandled rejection TypeError: Cannot read property 'kind' of undefined
    at /Users/doug/Projects/dougludlow/angular2-typings/node_modules/dts-generator/index.js:216:33
    at visit (/Users/doug/Projects/dougludlow/angular2-typings/node_modules/dts-generator/index.js:54:27)
    at visitNode (/Users/doug/Projects/dougludlow/angular2-typings/node_modules/typescript/lib/typescript.js:7409:20)
    at Object.forEachChild (/Users/doug/Projects/dougludlow/angular2-typings/node_modules/typescript/lib/typescript.js:7686:21)
    at visit (/Users/doug/Projects/dougludlow/angular2-typings/node_modules/dts-generator/index.js:60:16)
    at visitEachNode (/Users/doug/Projects/dougludlow/angular2-typings/node_modules/typescript/lib/typescript.js:7421:30)
    at Object.forEachChild (/Users/doug/Projects/dougludlow/angular2-typings/node_modules/typescript/lib/typescript.js:7578:24)
    at visit (/Users/doug/Projects/dougludlow/angular2-typings/node_modules/dts-generator/index.js:60:16)
    at processTree (/Users/doug/Projects/dougludlow/angular2-typings/node_modules/dts-generator/index.js:63:5)
    at writeDeclaration (/Users/doug/Projects/dougludlow/angular2-typings/node_modules/dts-generator/index.js:205:27)
    at /Users/doug/Projects/dougludlow/angular2-typings/node_modules/dts-generator/index.js:176:17
    at Array.some (native)
    at /Users/doug/Projects/dougludlow/angular2-typings/node_modules/dts-generator/index.js:164:34
    at tryCatcher (/Users/doug/Projects/dougludlow/angular2-typings/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/doug/Projects/dougludlow/angular2-typings/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/doug/Projects/dougludlow/angular2-typings/node_modules/bluebird/js/main/promise.js:70:37)
```
I went to line 216 of injex.js, which resolves to [line 279 in index.ts](https://github.com/SitePen/dts-generator/blob/master/index.ts#L279), and added a `node.parent &&` before `(node.parent.kind...` which got rid of the error and allowed the .d.ts file to generate and it works. But I'm not familiar with the code and not sure what's going on here exactly. Can anyone offer any insight?

This is the file I'm using to generate the .d.ts:
```
var dts = require('dts-generator').default;

dts({
    name: 'angular2',
    baseDir: './wwwroot/jspm_packages/npm/angular2@2.0.0-beta.1',
    out: 'typings/angular2/angular2.d.ts',
    files: [
        'core.d.ts',
        'http.d.ts',
        'common.d.ts',
        'router.d.ts',
        'testing.d.ts',
        'platform/browser.d.ts',
        'platform/server.d.ts'
    ]
});
```

**Comment by kitsonk** [comment]
Hmmm... Looks like some unsafe property accessing...
